# Generated by Django 4.2.29 on 2026-03-07 11:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 4), ('content', 5), ('features', 9), ('cards', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Material Icon name', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('title', 0), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Features Grid'}), 10: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 0), ('content', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Cards Grid'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
