# Generated by Django 4.2.29 on 2026-03-08 08:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_modularpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('content', 5), ('features', 9), ('cards', 13), ('tabs', 16), ('accordion', 19), ('slider', 23), ('toggle', 25), ('progress', 28), ('divider', 29)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image ID or external URL', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Material Icon name', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('title', 0), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Features Grid'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('image', 10), ('title', 0), ('content', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Cards Grid'}), 14: ('wagtail.blocks.StructBlock', [[('label', 0), ('content', 11)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('tabs', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('header', 0), ('content', 11)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('items', 18)]], {}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 0}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 100}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 1}), 23: ('wagtail.blocks.StructBlock', [[('label', 0), ('min_value', 20), ('max_value', 21), ('step', 22)]], {}), 24: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('label', 0), ('default_value', 24)]], {}), 26: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': '0 to 100'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('determinate', 'Determinate'), ('indeterminate', 'Indeterminate'), ('buffer', 'Buffer'), ('query', 'Query')]}), 28: ('wagtail.blocks.StructBlock', [[('label', 1), ('value', 26), ('mode', 27)]], {}), 29: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Visual Divider'})}),
        ),
    ]
