# Generated by Django 4.2.29 on 2026-03-08 08:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_modularpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('content', 5), ('features', 9), ('cards', 12), ('tabs', 15), ('accordion', 18), ('slider', 22), ('toggle', 24), ('progress', 27), ('divider', 28)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image ID or external URL', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Material Icon name', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('title', 0), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Features Grid'}), 10: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 0), ('content', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Cards Grid'}), 13: ('wagtail.blocks.StructBlock', [[('label', 0), ('content', 10)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('tabs', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('header', 0), ('content', 10)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.IntegerBlock', (), {'default': 0}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 100}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 1}), 22: ('wagtail.blocks.StructBlock', [[('label', 0), ('min_value', 19), ('max_value', 20), ('step', 21)]], {}), 23: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('label', 0), ('default_value', 23)]], {}), 25: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': '0 to 100'}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('determinate', 'Determinate'), ('indeterminate', 'Indeterminate'), ('buffer', 'Buffer'), ('query', 'Query')]}), 27: ('wagtail.blocks.StructBlock', [[('label', 1), ('value', 25), ('mode', 26)]], {}), 28: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Visual Divider'})}),
        ),
    ]
