# Generated by Django 4.2.29 on 2026-03-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_materialsnippet_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. BRAKES, ENGINE OIL, TYRES', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(help_text='e.g. Engine, Electronics, Bodywork', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], default='bike', max_length=10)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN/Chassis Number')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('inspection', 'Under Inspection'), ('working', 'Work in Progress'), ('testing', 'Final Testing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('issue_description', models.TextField(verbose_name='Customer Reported Issue')),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='home.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='In percentage', max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='home.servicejob')),
            ],
        ),
    ]
