# Generated by Django 4.2.29 on 2026-03-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_inspectionbucket_mechanic_vehicle_servicejob_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('amount_per_job', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialty_target', models.CharField(blank=True, help_text='Apply only to this specialty', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(default='9987', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_center_gstin',
            field=models.CharField(default='07AAAAA0000A1Z5', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=3)),
                ('year', models.IntegerField(default=2026)),
                ('base_salary', models.DecimalField(decimal_places=2, default=20000.0, max_digits=12)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='home.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave')], default='present', max_length=20)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='home.mechanic')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('mechanic', 'date')},
            },
        ),
    ]
