# Generated by Django 4.2.29 on 2026-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bonusrule_remove_invoice_tax_rate_invoice_cgst_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional banner image URL')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Flash Motors ERP', max_length=255)),
                ('owner_name', models.CharField(default='Abhijeet Raut', max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, default='Lorem Ipsum Street, New Delhi')),
                ('logo_url', models.URLField(blank=True, help_text='Direct link to shop logo')),
                ('theme_choice', models.CharField(choices=[('classic', 'Classic (Navy)'), ('emerald', 'Emerald Garden'), ('sunset', 'Sunset Glow'), ('cyberpunk', 'Cyberpunk Dark')], default='classic', max_length=20)),
                ('primary_color', models.CharField(default='#1a237e', help_text='Hex code for primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#ef5350', help_text='Hex code for secondary color', max_length=7)),
                ('gstin', models.CharField(default='07AAAAA0000A1Z5', max_length=15)),
            ],
            options={
                'verbose_name': 'Shop Setting',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=20),
        ),
    ]
