# Generated by Django 4.2.29 on 2026-03-14 08:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_moduleconfig_seasonaloffer_shopsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(help_text='Name of the mechanic or shop posting', max_length=150)),
                ('location', models.CharField(help_text='Vicinity or Area', max_length=200)),
                ('content', wagtail.fields.RichTextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='theme_choice',
            field=models.CharField(choices=[('classic', 'Classic (Navy)'), ('emerald', 'Emerald Garden'), ('sunset', 'Sunset Glow'), ('cyberpunk', 'Cyberpunk Dark'), ('midnight', 'Midnight Pro'), ('azure', 'Business Azure')], default='classic', max_length=20),
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.communitypost')),
            ],
            options={
                'verbose_name': 'Community Comment',
                'ordering': ['created_at'],
            },
        ),
    ]
