# Generated by Django 4.2.29 on 2026-03-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_communitypost_alter_shopsettings_theme_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Flash Motors ERP', max_length=255)),
                ('owner_name', models.CharField(default='Abhijeet Raut', max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, default='Lorem Ipsum Street, New Delhi')),
                ('logo_url', models.URLField(blank=True, help_text='Direct link to shop logo')),
                ('theme_choice', models.CharField(choices=[('classic', 'Classic (Navy)'), ('emerald', 'Emerald Garden'), ('sunset', 'Sunset Glow'), ('cyberpunk', 'Cyberpunk Dark'), ('midnight', 'Midnight Pro'), ('azure', 'Business Azure')], default='classic', max_length=20)),
                ('primary_color', models.CharField(default='#1a237e', help_text='Hex code for primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#ef5350', help_text='Hex code for secondary color', max_length=7)),
                ('gstin', models.CharField(default='07AAAAA0000A1Z5', max_length=15)),
                ('active_modules', models.ManyToManyField(blank=True, related_name='shops', to='home.moduleconfig')),
            ],
            options={
                'verbose_name': 'Shop Profile',
                'verbose_name_plural': 'Shop Profiles',
            },
        ),
        migrations.DeleteModel(
            name='ShopSettings',
        ),
        migrations.AddField(
            model_name='attendance',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='home.shop'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='home.shop'),
        ),
        migrations.AddField(
            model_name='inspectionbucket',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_buckets', to='home.shop'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.shop'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='home.shop'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='home.shop'),
        ),
        migrations.AddField(
            model_name='seasonaloffer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_offers', to='home.shop'),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='home.shop'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='home.shop'),
        ),
    ]
