# Generated by Django 4.2.29 on 2026-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_shop_delete_shopsettings_attendance_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleconfig',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
