# Generated by Django 4.2.29 on 2026-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_moduleconfig_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol (e.g. ₹, $)', max_length=5),
        ),
    ]
