# Generated by Django 4.2.29 on 2026-04-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_shop_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(help_text='ID of the person in the biometric system', max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=10)),
                ('raw_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Part Number')),
                ('category', models.CharField(choices=[('engine', 'Engine Parts'), ('electrical', 'Electrical'), ('body', 'Body & Exterior'), ('brakes', 'Braking System'), ('suspension', 'Suspension'), ('tyres', 'Tyres & Wheels'), ('consumables', 'Consumables (Oil, Coolant)'), ('accessories', 'Accessories')], default='engine', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase price per unit', max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('unit_of_measure', models.CharField(default='pcs', help_text='e.g. pcs, ltrs, sets', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory Part',
                'verbose_name_plural': 'Inventory Parts',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provident_fund_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase/Inward'), ('consumption', 'Consumption/Used in Job'), ('adjustment', 'Stock Adjustment'), ('return', 'Return to Supplier')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.inventorypart')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='bonusrule',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='inspectionbucket',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='seasonaloffer',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='servicejob',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='active_modules',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='Optional background splash image URL for the shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_account',
            field=models.OneToOneField(blank=True, help_text='Link this shop to a Wagtail User Account for isolated Admin access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ModuleConfig',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='service_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_consumptions', to='home.servicejob'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='mechanic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='home.mechanic'),
        ),
    ]
